{{- $config := .Values.service.config.secret -}}
{{- if and (not $config.existingSecret) $config.password -}}
{{- $secretName := printf "%s-secret" (include "dt4mob-fire-simulation.fullname" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "dt4mob-fire-simulation.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ $config.userName | quote }}
  password: {{ $config.password | quote }}
{{- end }}